# Generated by Django 3.2.12 on 2022-03-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarPickUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentvideo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
