# Generated by Django 3.2.10 on 2022-05-09 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GuitarPickUp', '0002_auto_20220305_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Feedback_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_class', models.BooleanField(blank=True, null=True)),
                ('middle_class', models.BooleanField(blank=True, null=True)),
                ('ring_class', models.BooleanField(blank=True, null=True)),
                ('pinky_class', models.BooleanField(blank=True, null=True)),
                ('note_played', models.CharField(blank=True, max_length=5, null=True)),
                ('note_class', models.BooleanField(blank=True, null=True)),
                ('feedback_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuitarPickUp.feedback')),
            ],
            options={
                'ordering': ['feedback_id'],
            },
        ),
    ]
