# Generated by Django 3.2.10 on 2022-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarPickUp', '0003_auto_20220509_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentvideo',
            old_name='Path',
            new_name='report',
        ),
        migrations.AddField(
            model_name='studentvideo',
            name='video_Path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentvideo',
            name='video_record',
            field=models.FileField(null=True, upload_to='records'),
        ),
    ]
